name: lastfm_dashboard
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^3.0.8
  rxdart: ^0.23.1
  synchronized: ^2.2.0
  provider: ^4.0.2
  path_provider: ^1.5.1
  charts_flutter: ^0.8.1
  shared_preferences: ^0.5.6+1
  sembast: ^2.1.2+3
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700