name: lastfm_dashboard
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0-dev.12 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.12.0+4
  rxdart: ^0.23.1
  synchronized: ^2.2.0
  path_provider: ^1.5.1
  charts_flutter: ^0.8.1
  shared_preferences: ^0.5.6+1
  sembast: ^2.4.1+1
  sembast_web: ^1.0.0
  cupertino_icons: ^0.1.2
  provider: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700